/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_deepmeditation_myapplication_Synth */

#ifndef _Included_com_example_deepmeditation_myapplication_Synth
#define _Included_com_example_deepmeditation_myapplication_Synth

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_deepmeditation_myapplication_Synth_play
(JNIEnv *, jclass, jfloat, jfloat,jdouble, jfloat, jint, jint);


JNIEXPORT void JNICALL Java_com_example_deepmeditation_myapplication_Synth_stopProcess
(JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
